# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit pkgpaper.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.align = "center",
                      # For text wrapping, install formatR
                      tidy.opts = list(width.cutoff = 20), tidy = TRUE)
library(ggplot2)
library(kableExtra)
library(insightmakeR1)
library(dplyr)
library(units)


## ----wrap-hook, include=FALSE-------------------------------------------------
library(knitr)
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = xfun::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})


## ----include=FALSE, out.width='100%'------------------------------------------
viz_str = "
digraph stock_and_flow {

  graph [layout = dot, rankdir = LR]
  margin=0 # in inches

  # Define variables
  'Hunger' [shape = 'circle', width = 1.5, fontsize = 16]
  'Food intake' [shape = 'circle', width = 1.5, fontsize = 16]
  'Compensatory\nbehaviour' [shape = 'circle', width = 1.5, fontsize = 16]

  # Define the links
  'Eating triggers' -> 'Food intake'  [label='+', fontsize = 18]
  'Hunger' -> 'Food intake' [label='+', fontsize = 18]
  'Food intake' -> 'Hunger' [label='-', fontsize = 18]
  
  'Hunger' -> 'Compensatory\nbehaviour' [label='-', fontsize = 18]
  'Compensatory\nbehaviour' -> 'Hunger' [label='+', fontsize = 18]
  
  'Food intake' -> 'Food intake' [label='-']
  
  'Food intake' -> 'Compensatory\nbehaviour' [label='+', fontsize = 18]
  'Compensatory\nbehaviour' -> 'Food intake' [label='-', fontsize = 18]

}
      "

pl = DiagrammeR::grViz(viz_str)
pl


## ----echo=FALSE---------------------------------------------------------------
functions_table <- data.frame(
  Building.Block = c("Stock", "Flow", "Auxiliary", "Graphical Function"),
  Description = c("Define the state of the system",
                  "Move material between Stocks and outside the model boundary", 
                  "Define static parameters or dynamic intermediate computation",
                  "Custom interpolation functions"),
  Example = c("People, products, beliefs, blood sugar, CO2 in atmosphere", "Birth rates, product order rates, revenue, sales", 
              "Fixed prices, sum of all Stocks, ratios of flows", "Interventions or events occurring at known times such as vaccines or storms")
)

kable(functions_table, format = "markdown", col.names = c("Building Block", "Purpose", "Example"),
      caption = "System Dynamics Building Blocks")


## ----eval = FALSE-------------------------------------------------------------
#> sdm = template("Crielaard2022")


## ----eval=FALSE, include=TRUE, out.width="100%"-------------------------------
#> URL = "https://insightmaker.com/insight/5LxQr0waZGgBcPJcNTC029/Crielaard-2022"
#> sdm = insightmaker_to_sdm(URL)


## -----------------------------------------------------------------------------
sdm = xmile(method = "euler", time_units = "hour", stop = 500) %>%
  build("Food.intake", "stock", eqn = "runif(1)", 
            inflow = list(c("Feeling.hunger", "Eating.triggers")), 
        outflow = list(c("Satiety", "Effect.of.compensatory.behavior")),
        label = "Food intake") %>%
  build("Hunger", "stock", eqn = "runif(1)", 
            inflow = "Losing.energy.by.compensatory.behavior", 
        outflow = "Food.intake.reduces.hunger") %>%
  build("Compensatory.behaviour", "stock", eqn = "runif(1)", 
        inflow = "Compensating.for.having.eaten", 
        outflow = "Satisfaction.with.hungry.feeling",
        label = "Compensatory behaviour") %>%
  build("Losing.energy.by.compensatory.behavior", "flow", 
        eqn = "(0.3 * Compensatory.behaviour) * ((1 - Hunger) / 1)", 
        label = "Losing energy by compensatory behavior") %>%
  build("Feeling.hunger", "flow", 
        eqn = "((0.8 * Hunger^a0) * Food.intake) * ((1 - Food.intake) / 1)", 
        label = "Feeling hunger") %>%
  build("Satiety", "flow", 
        eqn = "(1.3 * (Food.intake)) * ((1 - Food.intake) / 1)") %>%
  build("Food.intake.reduces.hunger", "flow", 
        eqn = "((1.4 * Food.intake^a0) * Hunger) * ((1 - Hunger) / 1)", 
        label = "Food intake reduces hunger") %>%
  build("Compensating.for.having.eaten", "flow", 
        eqn = "(Sig(a2 * Food.intake)) * ((1 - Compensatory.behaviour) / 1)", 
        label = "Compensating for having eaten") %>%
  build("Satisfaction.with.hungry.feeling", "flow",
        eqn = "(1.3 * Hunger * Compensatory.behaviour) * ((1 - Compensatory.behaviour) / 1)",
        label = "Satisfaction with hungry feeling") %>%
  build("Eating.triggers", "flow", 
        eqn = "(a1 * Food.intake) * ((1 - Food.intake) / 1)", 
        label = "Effect of eating triggers") %>%
  build("Effect.of.compensatory.behavior", "flow",
        eqn = "(2 * Compensatory.behaviour * Food.intake) * ((1 - Food.intake) / 1)", 
        label = "Effect of compensatory behavior") %>%
  build(c("a0", "a1", "a2"), "aux", eqn = c(1.31, 1.5, 0.38)) %>% 
  macro(name = "Sig", eqn = "function(x) 1 / (1 + exp(1)^(-x))")




## ----eval=FALSE, results='hide', out.width='100%'-----------------------------
#> get_build_code(template("SIR"))


## ----echo=FALSE---------------------------------------------------------------
functions_table <- data.frame(
  Property = c("label", "eqn", "units", "non_negative", "min", "max", "inflow", "outflow", "to", "from", "xpts", "ypts", "interpolation", "rule", "note"),
  Description = c("Name for plotting", "Equation (initial value in case of Stock)", "Units", "Enforce non-negativity", "Minimum value constraint",
                   "Maximum value constraint", "Variable flowing into Stock", "Variable flowing from Stock", "Target variable of Flow", "Source variable of Flow", "x-domain points of GF", "y-domain points of GF", "Interpolation method of GF", "Rule determining behaviour of GF outside of x-domain", "Add documentation to variable"),
  Example = c("`'Food intake'`", "`'sqrt(10)'`", "`'second'`", "`FALSE`", "`0`", "`300`", "`'Hunger'`", "`'Hunger'`", "`'Hunger'`", "`'Hunger'`", "`c(0, 1, 2, 3)`", "`c(10, 12, 14, 16)`", "`'linear'`", "`2`", "`'Subjectively assessed hunger on a scale from 0 to 10'`"),
  Stock = c("x", "x", "x", "x", "x", "x", "x", "x", "", "", "", "", "", "", "x"),
  Flow = c("x", "x", "x", "x", "x", "x", "", "", "x", "x", "", "", "", "", "x"),
  Auxiliary = c("x","x", "x", "x", "x", "x", "", "", "", "", "", "", "", "", "x"),
  GF = c("x","", "x", "", "x", "x", "", "", "", "", "x", "x", "x", "x", "x")
)

kable(functions_table, format = "markdown", col.names = c("Property", "Description", "Example", "Stock", "Flow", "Auxiliary", "GF"),
      caption = "Properties for each Building Block")


## ----echo=TRUE, results='hide'------------------------------------------------
sdm = build(sdm, "Food.intake", eqn = .5)


## ----echo=TRUE, results='hide'------------------------------------------------
peek(sdm, "Food.intake", "eqn")


## ----eval = FALSE, echo=TRUE, results='hide'----------------------------------
#> sdm = erase(sdm, name = "Food.intake")


## ----echo=TRUE, results='hide'------------------------------------------------
sdm = sim_specs(sdm, method = 'euler', time_units = 'day',
                  start = 0, stop = 500, dt = .01)


## -----------------------------------------------------------------------------
summary(sdm)


## ----out.width="140%"---------------------------------------------------------
plot(sdm)


## ----out.width="75%"----------------------------------------------------------
sim = simulate(sdm)
plot_stocks(sdm, sim$df)


## ----echo=FALSE---------------------------------------------------------------
functions_table <- data.frame(
  Function = c("`xmile()`", "`build()`", "`plot()`", "`summary()`", "`simulate()`", "`plot_stocks()`", "`compile()`", "`peek()`", "`sim_specs()`", "`model_units()`", "`macro()`", "`header()`", "`get_build_code()`", "`template()`", "`insightmaker_to_R()`"),
  Purpose = c("Create object of class xmile", "Add variable to model", "Plot model diagram", "Print summary of building blocks and variables", "Simulate model", "Plot timeseries of Stocks", "Get code to simulate model", "View desired variable properties", "Modify simulation specifications", "Define custom units", "Define global variables", "Define header of model", "Get code to build model from scratch", "Access template models", "Translate Insight Maker model to xmile object")
)

kable(functions_table, format = "markdown", col.names = c("Function", "Purpose"),
      caption = "Main functions in *sdbuildR*")


## ----eval = FALSE, results='hide'---------------------------------------------
#> sdm = build(sdm, "Food.intake", min = 0, max = 1) %>%
#>   build(sdm, "Losing.energy.by.compensatory.behavior", max = 1)


## ----echo=TRUE----------------------------------------------------------------
# Constraints of minimum and maximum value
constraints_def = list("Food.intake" = c(min = 0, max = 1),
                       "Losing.energy.by.compensatory.behavior" = c(max = 1))
constraints = get_logical_constraints(constraints_def) 
print(constraints)


## ----eval=FALSE, include=TRUE-------------------------------------------------
#> check_constraints(constraints, environment(), t)


## ----echo=FALSE, message=TRUE, warning=TRUE, error = TRUE---------------------
envir = new.env()
envir$Food.intake = 2
envir$Losing.energy.by.compensatory.behavior = 0
check_constraints(constraints, envir, 1)


## -----------------------------------------------------------------------------
times = seq(0, 50, by = .01)
step = make_step(times, start_t_step = 10, h_step = 20)
ramp = make_ramp(times, start_t_ramp = 10, end_t_ramp = 20)
pulse = make_pulse(times, start_t_pulse = 10, h_pulse = 10,
                   w_pulse = 5, repeat_interval = 20)
seasonal = make_seasonal(times, peak_time = 1, 'years')


## -----------------------------------------------------------------------------
sdm = sdm %>% build("ramp", "aux", eqn = "make_ramp(times, start_t_ramp = 0, end_t_ramp = 500, 
                    start_h_ramp = 1, end_h_ramp = 1)") %>%
  build("Eating.triggers", eqn = "(a1 * ramp(t) * Food.intake) * ((1 - Food.intake) / 1)") 

sim = simulate(sdm)
plot_stocks(sdm, sim$df)


## ----eval=FALSE---------------------------------------------------------------
#> sdm = sdm %>% erase("ramp") %>%
#>   build("ramp", "gf",
#>                     xpts = c(0, 300, 350, 400, 500),
#>                     ypts = c(.1, .5, .2, .5, 1.5))
#> 
#> 
#> sim = simulate(sdm)
#> plot_stocks(sdm, sim$df)


## ----eval=FALSE, include=FALSE, out.width="75%"-------------------------------
#> # sdm = build(sdm, "Food.intake.reduces.hunger", eqn = "((1.4 * add_delay(Food.intake, 1)^a0) * Hunger) * ((1 - Hunger) / 1)")
#> sdm = sdm %>%
#>   build("Satiety", eqn = "(1.3 * add_delay(Food.intake, 1)) * ((1 - Food.intake) / 1)")
#> 
#> sim = simulate(sdm)
#> plot_stocks(sdm, sim$df)


## ----eval=FALSE, include=FALSE, out.width="75%"-------------------------------
#> sdm = build(sdm, "Food.intake.reduces.hunger", eqn = "((1.4 * add_delayN(Food.intake, 1, 50)^a0) * Hunger) * ((1 - Hunger) / 1)")
#> sim = simulate(sdm)
#> plot_stocks(sdm, sim$df)


## ----eval=FALSE, include=FALSE, out.width="75%"-------------------------------
#> # sdm = build(sdm, "Food.intake.reduces.hunger", eqn = "((1.4 * add_delayN(Food.intake, 1, 10)^a0) * Hunger) * ((1 - Hunger) / 1)")
#> sdm = sdm %>%
#>   build("Compensating.for.having.eaten", eqn = "(Sig(a2 * max(add_past(Food.intake, 4)))) * ((1 - Compensatory.behaviour) / 1)")
#> 
#> sim = simulate(sdm)
#> plot_stocks(sdm, sim$df)


## ----echo=FALSE---------------------------------------------------------------
functions_table <- data.frame(
  Function = c("add_delay", "add_delayN", "add_past"),
  Purpose = c("Add a fixed delay", "Add a smooth delay of order N", "Retrieve past values"),
  Arguments = c("Variable, delay length, (default value)", "Variable, delay length, delay order, (default value)", "Variable, (past interval)")
)

kable(functions_table, format = "markdown", col.names = c("Function Name", "Purpose", "Arguments"),
      caption = "")


## ----eval=FALSE, include=TRUE-------------------------------------------------
#> arhive_var = c("Food.intake")
#> archive <<- setup_archive(archive_var, times)


## ----eval=FALSE, include=TRUE-------------------------------------------------
#> update_archive("archive", t, environment())


## ----eval=FALSE, include=TRUE-------------------------------------------------
#> past(archive, t, "Food.intake", pars$past_interval)
#> delay(archive, t, "Food.intake", pars$delay_length)


## ----eval=FALSE, include=TRUE-------------------------------------------------
#> xstart = c(xstart, setup_delayN("Food.intake_delayN_acc", xstart$Food.intake,
#>                                 pars$length_delayN, pars$order_delayN))


## ----eval=FALSE, include=TRUE-------------------------------------------------
#> Food.intake_delayN = delayN(input, S[grep('^Food.intake_delayN_acc', names(S))], pars$length_delay, pars$order_delay)


## -----------------------------------------------------------------------------
a = set_units(2, 'second')


## ----eval=FALSE, echo = TRUE, include=TRUE, results='hide'--------------------
#> sdm = build(sdm, "Food intake", units = "Kilocalories")


## -----------------------------------------------------------------------------
set_units(set_units(1, "year"), "day")


## -----------------------------------------------------------------------------
set_units(set_units(1, "common_year"), "day")
# set_units(set_units(1, "month"), "day")
# set_units(set_units(1, "common_month"), "day")


## ----eval = FALSE, results='hide'---------------------------------------------
#> sdm = model_units(sdm, name = "Satiety Hunger Score", eqn = "300 kilocalories", alias = "SHS") %>%
#>   build("Hunger", units = "SHS")


## ----eval=FALSE, include=TRUE-------------------------------------------------
#> # Add package for specifying units of each model element
#> if (!require('units')) install.packages('units')
#> library(units)
#> units_options(allow_mixed = T, simplify = T, set_units_mode = 'standard')


## ----eval=FALSE, include=FALSE------------------------------------------------
#> invisible(list(c(symbol = 'Satiety_Hunger_Score', def = '300 kilocalories', name = 'SHS')) %>%
#>             lapply(., install_custom_unit))


## ----eval=FALSE, include=TRUE, results='hide'---------------------------------
#> sdm = macro(sdm, name = "Sig", eqn = "function(x) 1 / (1 + exp(1)^(-x))")


## ----eval = FALSE,echo=FALSE, message=TRUE, warning=TRUE, error = TRUE--------
#> sdm %>%
#>   build("Food.intake", eqn = "Hunger") %>%
#>   build("Hunger", eqn = "Food.intake") %>%
#>   simulate()


## ----echo=FALSE---------------------------------------------------------------
functions_table <- data.frame(
  Building.Block = c("Stock", "Flow", "Auxiliary", "Graphical Function"),
  Description = c("Define the state of the system", "Move material between Stocks and outside the model boundary", 
                  "Define static parameters or dynamic intermediate computation",
                  "Interpolate between custom-defined functions"),
  Example = c("Populations", "Birth rates, product order rates", 
              "", "")
)

kable(functions_table, format = "markdown", col.names = c("Building Block", "Purpose", "Example"),
      caption = "System Dynamics Building Blocks")


## ----out.width="100%"---------------------------------------------------------
compile(sdm)

