# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown.yaml

permissions: read-all

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      NOT_CRAN: "true"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      # Necessary to prevent CHOLMOD error
      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11.5'

      # Print Julia environment variables
      - name: Print Julia environment
        run: |
          echo "JULIA_BINDIR: $JULIA_BINDIR"
          echo "PATH: $PATH"
          which julia
          julia --version
        shell: bash

      # Install specific Julia packages
      - name: Install Julia packages
        run: |
          julia -e '
            using Pkg
            Pkg.add(name="OrdinaryDiffEq", version="6.98")
            Pkg.add(name="DiffEqCallbacks", version="4.8")
            Pkg.add(name="DataFrames", version="1.7")
            Pkg.add(name="Distributions", version="0.25")
            Pkg.add(name="Statistics", version="1.11")
            Pkg.add(name="StatsBase", version="0.34")
            Pkg.add(name="Unitful", version="1.23")
            Pkg.add(name="DataInterpolations", version="8.1")
            Pkg.add(name="Random", version="1.11")
            Pkg.add(name="CSV", version="0.10")
            Pkg.add(name="SciMLBase", version="2.102")
            Pkg.precompile()
          '
        shell: bash

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: docs
