# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown.yaml

permissions: read-all

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, any::JuliaCall, local::.
          needs: website

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11.5'

      - name: Verify Julia installation
        run: |
          echo "Checking Julia installation..."
          julia --version
          which julia
          echo "Julia binary: $(which julia)"
          julia -e 'println("Julia environment: ", Base.active_project())'
          julia -e 'using Pkg; Pkg.status()'
          echo "Julia installation verified."

      - name: Inspect JuliaCall scripts
        run: |
          echo "Locating and inspecting JuliaCall scripts..."
          Rscript -e 'cat(system.file("julia/setup.jl", package = "JuliaCall"), "\n")' > setup.jl
          Rscript -e 'cat(system.file("julia/install_dependency.jl", package = "JuliaCall"), "\n")' > install_dependency.jl
          echo "Contents of setup.jl:"
          cat setup.jl
          echo "Contents of install_dependency.jl:"
          cat install_dependency.jl
          echo "JuliaCall scripts inspection complete."

      - name: Test JuliaCall setup.jl
        run: |
          echo "Testing setup.jl in standalone Julia session..."
          julia -e 'try; include("setup.jl"); println("setup.jl executed successfully"); catch e; println("Error in setup.jl: ", e); exit(1); end'
          echo "setup.jl test complete."

      - name: Test JuliaCall install_dependency.jl
        run: |
          echo "Testing install_dependency.jl in standalone Julia session..."
          julia -e 'try; include("install_dependency.jl"); println("install_dependency.jl executed successfully"); catch e; println("Error in install_dependency.jl: ", e); exit(1); end'
          echo "install_dependency.jl test complete."

      - name: Install Julia packages Suppressor and RCall
        run: |
          echo "Installing Suppressor and RCall..."
          julia -e 'using Pkg; Pkg.add(["Suppressor", "RCall"]); Pkg.build("RCall"); Pkg.status()'
          echo "Julia package installation complete."

      - name: Initialize Julia environment
        run: |
          echo "Running use_julia()..."
          Rscript -e 'library(sdbuildR); print(packageVersion("JuliaCall")); use_julia(version="1.11.5", force=TRUE)'
          echo "use_julia() complete."
          echo "Post-use_julia Julia environment:"
          julia -e 'println("Julia environment: ", Base.active_project())'
          julia -e 'using Pkg; Pkg.status()'

      - name: Build site
        run: |
          echo "Building pkgdown site..."
          Rscript -e 'pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)'
          echo "Site build complete."

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: docs
